#docker-compose down -v -f -> deletes the volumes if entrypoint has
#to be rerun
version: '3.7'

services:
  node1:
    image: 'docker.io/bitnami/mariadb-galera:10.2'
    ports:
      - '3306:3306'
      - '4444:4444'
      - '4567:4567'
      - '4568:4568'
    volumes:
      - 'node1d:/bitnami/mariadb'
      - ./node1d/mariadb.setup/:/docker-entrypoint-initdb.d
    restart: unless-stopped
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
      - REPLICATION_PASSWORD=test
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=vsTest
      - MYSQL_USER=public
      - MYSQL_PASSWORD=public
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      - MARIADB_REPLICATION_USER=test
      - MARIADB_REPLICATION_PASSWORD=test
      - MARIADB_GALERA_CLUSTER_NAME=myCluster
      - MARIADB_GALERA_MARIABACKUP_USER=backupTest
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backupTest
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://172.20.3.251,172.20.3.252,172.20.3.253
      - MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes
    networks:
      frontend:
        ipv4_address: 172.20.3.251
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 2


  node2:
    image: 'docker.io/bitnami/mariadb-galera:10.2'
    volumes:
      - 'node2d:/bitnami/mariadb'
      - ./node2d/mariadb.setup/:/docker-entrypoint-initdb.d
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
      - REPLICATION_PASSWORD=test
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=vsTest
      - MYSQL_USER=public
      - MYSQL_PASSWORD=public
      - MARIADB_REPLICATION_USER=test
      - MARIADB_REPLICATION_PASSWORD=test
      - MARIADB_GALERA_CLUSTER_NAME=myCluster
      - MARIADB_GALERA_MARIABACKUP_USER=backupTest
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backupTest
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://172.20.3.251,172.20.3.252,172.20.3.253
      - MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes
    networks:
      frontend:
        ipv4_address: 172.20.3.252
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 2

  node3:
    image: 'docker.io/bitnami/mariadb-galera:10.2'
    volumes:
      - 'node3d:/bitnami/mariadb'
      - ./node3d/mariadb.setup/:/docker-entrypoint-initdb.d
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
      - REPLICATION_PASSWORD=test
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=vsTest
      - MYSQL_USER=public
      - MYSQL_PASSWORD=public

      - MARIADB_REPLICATION_USER=test
      - MARIADB_REPLICATION_PASSWORD=test
      - MARIADB_GALERA_CLUSTER_NAME=myCluster
      - MARIADB_GALERA_MARIABACKUP_USER=backupTest
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backupTest
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://172.20.3.251,172.20.3.253,172.20.3.253
      - MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes
    networks:
      frontend:
        ipv4_address: 172.20.3.253
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 2

volumes:
  node1d:
    driver: local
  node2d:
    driver: local
  node3d:
    driver: local


networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.3.0/24